export const foundingChapterBrothers: {
  className: string;
  brothers: string[];
}[] = [
  {
    className: 'Founding Fathers',
    brothers: [
      'Sean Aguon',
      'Jeffrey Chao',
      'Charleston Chua',
      'Christopher Doan',
      'Andy Ha',
      'Steven Ly',
      'Hector Miguel',
      'Tommy On',
      'Zephyrene Villaluz',
      'Michael Wang',
      'Anthony Yi',
    ],
  },
  {
    className: 'Alpha',
    brothers: [
      'Jefferson Bustarde',
      'Markus Caligdong',
      'Jeff Creedon',
      'Steven Flores',
      'TJ Garcia',
      'Andrew Lau',
      'Sang Lee',
      'Travis Nguyen',
      'Daniel Taing',
      'Gabriel Uy',
      'Anthony Villalba',
    ],
  },
  {
    className: 'Beta',
    brothers: [
      'Mark Dave Almachar',
      'Abraham Cheng',
      'Michael Chewjalearn',
      'Justin Choi',
      'Christopher Frias',
      'Scotty Huynh',
      'Kalena Pelekai-Wai',
      'Daniel Vu',
    ],
  },
  {
    className: 'Gamma',
    brothers: [
      'Tony Boffelli',
      'Ronnie Corcuera',
      'Aren Hirano',
      'Erik Ibarra',
      'Marcus Krueger',
      'James Kuzhipalla',
      'Kawena Lee',
      'Kevin Rodriguez',
    ],
  },
  {
    className: 'Delta',
    brothers: [
      'Robert Aker',
      'Emil Almachar',
      'Kamran Baig',
      'Steven Eng',
      'David Perez',
      'Stevanus Pradipa',
      'David Silva',
      'David Waihenya',
    ],
  },
  {
    className: 'Epsilon',
    brothers: [
      'Robert Alvarez',
      'Deo Bustarde',
      'Ryan Fong',
      'Warren Kao',
      'Danny Lee',
      'Steven Leung',
      'Ian Nato',
      'Dennis Park',
      'Jason Phan',
      'David Ramirez',
      'Jiruth Samerthai',
      'Sonny Tao',
    ],
  },
  {
    className: 'Zeta',
    brothers: [
      'Ian Cabanilla',
      'Austin Eskola',
      'Steven Lam',
      'Tyler McWilliams',
      'Kevin Rosario',
      'David Thantacheva',
      'Kevin Wang',
    ],
  },
  {
    className: 'Eta',
    brothers: ['AJ Cabuang', 'Andrew Helige', 'Tyler Kinney'],
  },
  {
    className: 'Theta',
    brothers: ['Kavindu Amarasinghe', 'RB Rom', 'Joshoua Staana'],
  },
  {
    className: 'Iota',
    brothers: [
      'Ricardo Aker',
      'Geoffrey Kirk Alcaraz',
      'Christian Aranas',
      'William Brown',
      'Paul Caraos',
      'Nathan Hagarty',
      'Anthony Ko',
      'Paul Ko',
      'Danny Phung',
      'Jordan Serrano',
    ],
  },
  {
    className: 'Kappa',
    brothers: [
      'Josh Cano',
      'Jacob Davis',
      'Gabe Delos Santos',
      'Victor Li',
      'Chris Ngo',
      'Baltazar Pulido',
      'Mickey Rosal',
      'Mauricio Solorio',
    ],
  },
  {
    className: 'Lambda',
    brothers: [
      'Raul Esteves',
      'Hung Le',
      'Nevin Ly',
      'Floyd Ngov',
      'Will Peruel',
      'Damian Van',
    ],
  },
  {
    className: 'Mu',
    brothers: [
      'Christian Corabo',
      'Jeff Kwong',
      'Jericho Sadorra',
      'Sirasit Punnanithi',
    ],
  },
  {
    className: 'Nu',
    brothers: ['Ryan Kim', 'Raphael Perry', 'Kevin Samuel'],
  },
  {
    className: 'Xi',
    brothers: ['Juan Carlos Comahig', 'Allister Magalued', 'Ivan Samuel'],
  },
  {
    className: 'Omicron',
    brothers: [
      'Alan Cruz',
      'Brendan Hopson',
      'Jaemin Lee',
      'Benjamin Ly',
      'Isaiah Marcello',
      'Micah Soga',
      'Ethan Tsuneta',
      'Tim Wong',
    ],
  },
  {
    className: 'Pi',
    brothers: ['Derick Nguyen', 'Alex Pham', 'Joey Pontillas'],
  },
  {
    className: 'Rho',
    brothers: ['Saebyuk Lee', 'Nathan Toralba', 'Albert Tran'],
  },
  {
    className: 'Sigma',
    brothers: [
      'Keanu Aloua',
      'Marlou DeCastro',
      'Justin Fan',
      'Josh Insorio',
      'Brent Kuruma',
      'Brian Nguyen',
      'Kenneth Saronghilo',
      'Marcus Son',
    ],
  },
  {
    className: 'Tau',
    brothers: ['Joseph Cano', 'Vincent Lee', 'Ian Sin'],
  },
  {
    className: 'Upsilon',
    brothers: [
      'Nicholas Hong',
      'Junior Macatlang',
      'Henry Shi',
      'Carlos Vega-Reza',
    ],
  },
  {
    className: 'Phi',
    brothers: [
      'Eadrian Carreon',
      'Jeremy Co',
      'Dylan Dang',
      'Morgan Hunt',
      'Gavin Ide',
      'Sean Luna',
      'Jhamin Mondragon',
      'Larsen So',
      'Shangqi Xue',
    ],
  },
  {
    className: 'Chi',
    brothers: [
      'Jordan Cadelina',
      'Chris Fernandez',
      'Cole Gilliam',
      'Joel Palabay',
      'Mateo Sicento',
      'Lourenz Victoria',
    ],
  },
  {
    className: 'Psi',
    brothers: ['Andre Oen', 'Adam Santos'],
  },
  {
    className: 'Omega',
    brothers: [],
  },
  {
    className: 'Alpha Alpha',
    brothers: [],
  },
  {
    className: 'Alpha Beta',
    brothers: [],
  },
];
